-- +goose Up

CREATE TABLE IF NOT EXISTS stock_stats (
    id SERIAL PRIMARY KEY,
    stock_header_id INT REFERENCES stock_headers(id) ON DELETE CASCADE,

    market_cap REAL NOT NULL,
    pb_ratio REAL,
    pe_ratio REAL,
    div_yield REAL,
    book_value REAL,
    eps_ttm REAL,
    roe REAL,
    industry_pe REAL,
    capped_type TEXT,
    dividend_yield_in_percent REAL,
    face_value INT,
    debt_to_equity REAL,
    return_on_assets REAL,
    return_on_equity REAL,
    operating_profit_margin REAL,
    net_profit_margin REAL,
    quick_ratio REAL,
    cash_ratio REAL,
    debt_to_asset REAL,
    ev_to_sales REAL,
    ev_to_ebitda REAL,
    earnings_yield REAL,
    sector_pb REAL,
    sector_div_yield REAL,
    sector_roe REAL,
    sector_roce REAL,
    price_to_ocf REAL,
    price_to_fcf REAL,
    roic REAL,
    pe_premium_vs_sector REAL,
    pb_premium_vs_sector REAL,
    div_yield_vs_sector REAL,
    current_ratio REAL,
    sector_pe REAL,
    price_to_sales REAL,
    peg_ratio REAL
);
